title: Medical Roleplay Guidebook
description: A guidebook for medical roleplayers in the GTA 5 universe
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
url: https://medrp.agrra.net

aux_links:
  Guide Repository: https://github.com/dangitrp/medical-rp-guide

plugins:
  - jekyll-default-layout