title: Medical Roleplay Guidebook
description: A guidebook for medical roleplayers in the GTA 5 universe
theme: just-the-docs
logo: "/assets/images/logo.jpg"
color_scheme: dark
url: https://medrp.agrra.net

aux_links:
  Guide Repository: https://github.com/dangitrp/medical-rp-guide

plugins:
  - jekyll-default-layout