title: Medical Roleplay Guidebook
description: A guidebook for medical roleplayers in the GTA 5 universe
color_scheme: dark
theme: just-the-docs
logo: "/assets/images/logo.jpg"

url: https://medrp.agrra.net

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout