title: Medical Roleplay Guidebook
description: A guidebook for medical roleplayers in the GTA 5 universe
remote_theme: pmarsceill/just-the-docs

url: https://medrp.agrra.net

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout