title: Medical Roleplay Guidebook
description: A guidebook for medical roleplayers in the GTA 5 universe
remote_theme: just-the-docs/just-the-docs
url: https://medrp.agrra.net

aux_links:
  Guide Repository: https://github.com/dangitrp/medical-rp-guide

plugins:
  - jekyll-default-layout

color_scheme: dark

nav_external_links_new_tab: true
heading_anchors: true

ga_tracking: G-409CW9NX9F